_target_: src.models.full_atom.diffuser.se3_diffuser.SE3Diffuser
se3_conf:
  diffuse_trans: true
  diffuse_rot: true
  r3:
    min_b: 0.1
    max_b: 20.0
    coordinate_scaling: 0.1
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: "logarithmic"
    cache_dir: ".cache/"
    use_cached_score: False