# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  refresh_rate: 1 # progress bar update rate, set to 0 to disable display
  leave: True # leave the finished progress bar in the terminal at the end of the epoch
